#--------------------------------------------------------#
# Ingress Controller
#--------------------------------------------------------#
# Routes external HTTP traffic to internal services
# Includes rewrite rules to strip path prefixes
# Requires NGINX ingress controller to be installed in the cluster (acts as reverse proxy)

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jakob-ingress
  namespace: jakob
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /jakob/vote(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: jakob-service-vote
            port:
              number: 80
      - path: /jakob/result(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: jakob-service-result
            port:
              number: 80
