#--------------------------------------------------------#
# Kubernetes Deployment: Worker App
#--------------------------------------------------------#
# Thw Worker moves votes from Redis queue to PostgreSQL database
# No service needed as it doesn't expose ports / doesn't accept incoming traffic

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakob-deployment-worker
  namespace: jakob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jakob-worker
      owner: jakob
  template:
    metadata:
      labels:
        app: jakob-worker
        owner: jakob
    spec:
      containers:
      - name: worker
        image: jakobflechsenhar/worker:latest
        env:
        - name: POSTGRES_HOST
          value: jakob-service-postgres # PostgreSQL service name
        - name: POSTGRES_PORT
          value: "5432"                 # PostgreSQL port (string)
        - name: POSTGRES_DB
          value: votes                  # Database name (must match PostgreSQL)
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: REDIS_HOST
          value: jakob-service-redis    # Redis service name
        resources:
          requests:
            memory: "128Mi"             # Minimum memory
            cpu: "100m"                 # Minimum CPU (0.1 core)
          limits:
            memory: "256Mi"             # Maximum memory
            cpu: "200m"                 # Maximum CPU (0.2 core)
